typography_spectrum: 0.4242742
color:
  saturation: 0.5290651
  brandStrength: 0.6265042
  rhythmicContrast: 0.3088077
  brandColors:
    - '#FFFFFF'
    - '#73AFB7'
    - '#5D6F7B'
    - '#C5C5C5'
    - '#151515'
  lightness: 1
layout_spectrum: 0.1197637
author:
  name: Jared East
  email: jared@jaredeast.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e34464bf-fd8a-4b29-b28c-c3d9c279e0b3.jpg
name: The Human Element
navigation:
  - name: Decisions
    id: 45c54ef4-ac08-4dea-bc3e-4dede89b2ab4
    type: content
  - name: 'Behavior '
    id: 60d36155-2c88-409a-8527-f7901b988aa5
    type: content
  - name: Health
    id: 4a857e78-d708-4bb1-9f65-61c9f10b04b2
    type: content
  - name: Fitness
    id: ecebd271-0b78-4abb-a450-e9dbaa2321c5
    type: content
  - name: 'Cooperation '
    id: 91b5ccda-9389-4e16-bfa9-b9f631a2bb58
    type: content
  - name: Conflict
    id: 0b2265a0-c032-4d19-bc14-12176479da37
    type: content
  - name: About
    id: c9f211c1-9747-49fe-be01-c86189107f6a
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8fb4b4a0-b921-44ac-9b3b-6ddfb594130f.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: the Human Element
description: 'Brains, Bodies and Tribes'
