layout_spectrum: 0.4895697
typography_spectrum: 0.4242742
color:
  saturation: 0.5290651
  brandStrength: 0.6265042
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#73AFB7'
    - '#5D6F7B'
    - '#C5C5C5'
    - '#151515'
  rhythmicContrast: 0.3088077
name: The Human Element
